import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Nav/Nav";
import BinaryBackground from "@/components/BackgroundDynamic"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Miguel Nicolas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BinaryBackground>
        </BinaryBackground>
        <div className=" flex flex-row bg-black bg-opacity-65 h-full w-dvh">
          <Navbar></Navbar>
          {children}
        </div>
      </body>

    </html>
  );
}
